name: depremproje
description: "depmo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  http: ^1.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  geolocator: ^10.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/response.json
    - assets/images/depmo_logo.png
    - assets/sounds/whistle.mp3

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/depmo_logo.png"
