// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AptrNA8tIpoboM21he-kVltCeJpcK7E',
    appId: '1:819724787356:android:09bfc6b77dad74fb18d759',
    messagingSenderId: '819724787356',
    projectId: 'deprem-uygulamasi-41624',
    databaseURL: 'https://deprem-uygulamasi-41624-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deprem-uygulamasi-41624.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuhfI1RfJev5rY5ywl6XwDo2R1sDxBVEM',
    appId: '1:819724787356:ios:43566c902822435918d759',
    messagingSenderId: '819724787356',
    projectId: 'deprem-uygulamasi-41624',
    databaseURL: 'https://deprem-uygulamasi-41624-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deprem-uygulamasi-41624.firebasestorage.app',
    iosBundleId: 'com.example.depremproje',
  );
}
